saya update file note saya saja
moetadashi/pengalaman-belajar pull request #4
Opened 2024-08-10 15:08 UTC by moeclay

2024-08-10 15:13 UTC, moetadashi commented on meclay_note.txt
> +hanya ini yang diupdate pada latihan kali ini
perlu ditambah nama pembuat di bawah baris ini.

2024-08-10 15:15 UTC, moetadashi commented on meclay_note.txt
> +hanya ini yang diupdate pada latihan kali ini
baik akan segera ditambahkan

2024-08-10 15:17 UTC, moetadashi requested changes
buat perubahan refisi nya

2024-08-10 15:21 UTC, moetadashi approved these changes

2024-08-10 15:22 UTC, closed without merging

2024-08-11 03:00 UTC, moeclay commented on meclay_note.txt
> +hanya ini yang diupdate pada latihan kali ini
baik saya perbaiki kembali